### ISSUE TITLE
Lightwalletd Production Deployment epic

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#127]
Story: As a mobile wallet server administrator I would like a secure, easily deployable, and well documented lightwalletd server so that I can confidently deploy lightwalletd into production.

Criteria:
- [x] contains developer and contribution guidelines
- [x] contains a versioning policy (#130)
- [x] is versioned (#130)
- [x] DOCKERFILE exists and deploys a functioning mainnet lightwalletd (#128)
- [x] Full deployment documentation
- [x] Full internal security review completed and high and medium priority items are remedied (#129)
- [ ] **TODO**: Cost Baseline/User
- [ ] **TODO**: Scalability baseline (number of concurrent users)
- [ ] Developer focused API documentation exists and is publicly accessible (#131)
