### ISSUE TITLE
Reliable Lightwalletd Epic

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#133]
As a wallet developer, I need a reliable and resilient server from which to download block data so that my user experience is consistent. 

Criteria:
1) Lightwalletd can fail, restart, and reacquire the correct state for the following reasons:
- [ ] Out of Memory
- [ ] Host system crashes and then recovers for any reason
- [ ] Persistent state failures
- [ ] Loss of network
- [ ] Loss of connection with zcashd
2) For all above failures there is a descriptive error message that can be accessed by clients connected to the server
3) All failure modes that are handled are documented
4) Error messages are documented
