### ISSUE TITLE
Lightwalletd Performance Epic

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#135]
As a wallet developer I would like to be have a performant and easy to maintain lightwallet server to deliver blocks in a convenient and bandwidth efficient way.

Criteria:
(These are still loose and based on research, generally not ready for work)
- [x] Research and settle on V1 of the API taking into account feedback from ZECWallet and other partners (#134)
- [x] Research performance and scaling projections to satisfy 2 year growth trajectory for lightwalletd
- [x] Implement findings from API research
- [x] Research methods to achieve scaling and performance baselines
- [x] Implement scaling and performance baselines
